apiVersion: apps/v1
kind: Deployment
metadata:
  name: mangotodo
  labels:
    app: mangotodo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mangotodo
  template:
    metadata:
      labels:
        app: mangotodo
    spec:
      containers:
        - name: mangotodo
          image: ghcr.io/middleware-labs/otel-demo-mangotodo:latest
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_HOST
              value: mongo:27017
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mangotodo-svc
spec:
  selector:
    app: mangotodo
  ports:
    - port: 3000
      targetPort: 3000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: mongo-pvc
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity:
    storage: 256Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /tmp/db
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongo
  ports:
    - port: 27017
      targetPort: 27017
  type: ClusterIP