apiVersion: apps/v1
kind: Deployment
metadata:
  name: mangotodo
  labels:
    app: mangotodo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mangotodo
  template:
    metadata:
      labels:
        app: mangotodo
    spec:
      containers:
        - name: mangotodo
          image: ghcr.io/middleware-labs/otel-demo-mangotodo:latest
          ports:
            - containerPort: 3000
          env:
            - name: PGDB_HOST
              value: opentelemetry-demo-ffspostgres
            - name: PGDB_USER
              value: ffs
            - name: PGDB_PASS
              value: ffs
            - name: PGDB_DB
              value: ffs
            - name: MW_ACCOUNT_KEY
              value: <{.MW_ACCOUNT_KEY}>
            - name: MW_AGENT_SERVICE
              value: mw-service.mw-agent-ns.svc.cluster.local
            - name: MONGO_HOST
              value: mongodb:27017
          imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: mangotodo
spec:
  selector:
    app: mangotodo
  ports:
    - port: 3000
      name: mangotodo
      targetPort: 3000
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  selector:
    matchLabels:
      app: mongodb
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
        - name: mw-host-agent-sidecar
          image: ghcr.io/middleware-labs/mw-host-agent:mongo-k8s-demo
          imagePullPolicy: Always
          env:
            - name: MW_API_KEY
              value: <{.MW_ACCOUNT_KEY}>
            - name: MW_TARGET
              value: https://spbnu.middleware.io:443
            - name: MW_CONFIG_CHECK_INTERVAL
              value: "0"
            - name: MW_POSTGRES_USER
              value: <{.MW_POSTGRES_USER}>
            - name: MW_POSTGRES_PASSWORD
              value: <{.MW_POSTGRES_PASSWORD}>
            - name: MW_POSTGRES_DB
              value: <{.MW_POSTGRES_DB}>
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      name: mongodb
      targetPort: 27017
  type: ClusterIP
