# Copyright The OpenTelemetry Authors
# SPDX-License-Identifier: Apache-2.0


receivers:
  otlp/mw-apms:
    protocols:
      grpc:
        endpoint: 0.0.0.0:9319
      http:
        endpoint: 0.0.0.0:9320
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"
  otlp:
    protocols:
      grpc:
      http:
        cors:
          allowed_origins:
            - "http://*"
            - "https://*"

exporters:
  otlp/jaeger:
    endpoint: "jaeger:4317"
    tls:
      insecure: true
  logging:
    loglevel: debug
  otlp/middleware:
    endpoint: ${MW_TARGET}
    headers:
      authorization: ${MW_API_KEY}
    sending_queue:
      enabled: true
      num_consumers: 100
      queue_size: 10000

processors:
  batch:
  filter:
    metrics:
      exclude:
        match_type: strict
        metric_names:
          - queueSize

# connectors:
#   spanmetrics:

service:
  pipelines:
    traces:
      receivers: [otlp, otlp/mw-apms]
      processors: [batch]
      exporters: [logging, otlp/middleware, otlp/jaeger]
    metrics:
      receivers: [otlp, otlp/mw-apms, 
      # spanmetrics
      ]
      processors: [filter, batch]
      exporters: [logging, otlp/middleware]
    logs:
      receivers: [otlp, otlp/mw-apms]
      processors: [batch]
      exporters: [logging, otlp/middleware]
  telemetry:
    logs:
      level: debug
